### ISSUE TITLE
Reiter Erweitert ist nicht mehr da

### ISSUE THREAD

**Issue by Nightwing0815** [cliffparnitzky/TinyMceImageEnhancement#1]
Hallo Cliff,

mir fiel gerade bei einer Seite nach dem Update auf 4.9.0 auf, das der Reiter Erweitert nicht mehr da ist, also für die z.B seitlichen imagemargin Abstände?!?
Hab gerade bei meinen anderen Installationen (4.8.8) geschaut: auch da ist er weg.
Ich kann Dir leider nicht sagen, seit wann das so ist...

![1](https://user-images.githubusercontent.com/54181775/75082050-12b75b00-5512-11ea-8112-6e00ca1d230f.PNG)

ToM

**Comment by cliffparnitzky** [comment]
Vielen Dank für den Hinweis. Nach einer Analyse habe ich die Ursache ermitteln können.

Siehe dazu https://github.com/cliffparnitzky/TinyMcePluginLoader/issues/14

**Comment by cliffparnitzky** [comment]
Gefixt mit https://github.com/cliffparnitzky/TinyMcePluginLoader/commit/c3f647c1558ff8f6d7a6928b9f1a4bfd890a10e3

Bitte mal via Composer/Contao Manager updaten, so dass https://packagist.org/packages/cliffparnitzky/tiny-mce-plugin-loader auf Version 2.1.10 aktualisiert wird.
